"""
Phase 4C automated tests (spec Step 12): proves the point-in-time pipeline
(backend/pit/build_snapshots.py) is data-source configurable, that the
synthetic and original experiments stay isolated from each other, and
that the synthetic run introduces zero leakage and zero mutation of any
immutable/archived file.
"""
import hashlib
import json

import joblib
import pandas as pd
import pytest

import build_snapshots as bs

# Hashes recorded at the start of the Phase 4C session (before any code in
# this file existed) -- see docs/04C_SYNTHETIC_DATA_EXPERIMENT.md section 6.
EXPECTED_ORIGINAL_RAW_HASHES = {
    "raw_members.csv": "b94df89ed042a8feaa1bb46d7939e124fb9f6b03308b11da045412a427b78c46",
    "raw_ed_visits.csv": "f8db1839fb7966c4230c771252a3b935c318d0838de9258dc29de42d042f5d47",
    "raw_care_history.csv": "358d3033faa4e0529aed834cd8847f72d0b5d4ca51fa76748523fab790c81657",
}
EXPECTED_SYNTHETIC_RAW_HASHES = {
    "raw_members.csv": "00cb4023eb20876fd9b9cd2b3b3e283c8e6681f1452a6c3e9cbfda37f0bd2373",
    "raw_ed_visits.csv": "bb3c9505a836b8c70813aa2fdd62f628bd871f657fa1dfca1330799d27ce88c0",
    "raw_care_history.csv": "20fdcb836f6abbbd1b1b70d7c1f7cd2279f5c519251322944b0ca7109a66db1a",
}
# Hashes of the archived original-experiment copy, captured immediately
# after copying data/derived/*.csv|json -> data/derived/original/ in this
# phase. This archived copy is never regenerated by any code and must stay
# byte-identical forever -- it is the permanent historical-evidence record.
EXPECTED_ARCHIVED_ORIGINAL_HASHES = {
    "train_snapshot.csv": "1b6799904302398d95b478ca2a1e33d0b206fcc1983151b743f01cdbb7a534eb",
    "validation_snapshot.csv": "a19dad00c4a8329074f7dcba94357506fd004ff7798c82d7d8b7313f13c9b70f",
    "test_snapshot.csv": "1d4e8b22ede975cdad43379dd0566d38b597e270e8dbd1fcf3a1d85d8989ac1a",
    "feature_manifest.json": "fdd661653638649e3da02087bbdcd95a70f754f69e3218e0155cf8368cbd657a",
    "snapshot_metadata.json": "428e31b408334392df66929bcd9594074290b0edd2c9854022b158b986d59c7e",
    "validation_report.json": "e783ec7fe1c518daa3d959b6300504e2acbe18bfb12a54f3e395db5b125710e0",
}


def _sha256(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ---- 1. Original path configuration works ----

def test_original_path_configuration_works(tmp_path):
    result = bs.main(
        members_path=bs.RAW_MEMBERS, ed_path=bs.RAW_ED, care_path=bs.RAW_CARE,
        output_dir=tmp_path / "original_via_explicit_paths",
        dataset_id="original", synthetic=False,
    )
    assert result["validation_report"]["all_passed"]
    assert result["dataset_id"] == "original"
    assert result["synthetic"] is False
    assert len(result["snapshots"]["train"]) == 10000


# ---- 2. Synthetic path configuration works ----

def test_synthetic_path_configuration_works(tmp_path):
    result = bs.main(
        members_path=bs.SYNTHETIC_RAW_MEMBERS, ed_path=bs.SYNTHETIC_RAW_ED, care_path=bs.SYNTHETIC_RAW_CARE,
        output_dir=tmp_path / "synthetic_via_explicit_paths",
        dataset_id="synthetic_uc07_v1", synthetic=True,
    )
    assert result["validation_report"]["all_passed"]
    assert result["dataset_id"] == "synthetic_uc07_v1"
    assert result["synthetic"] is True
    assert len(result["snapshots"]["train"]) == 10000


# ---- 3. Synthetic output directory is isolated ----

def test_synthetic_output_directory_is_isolated():
    assert bs.SYNTHETIC_DERIVED_DIR != bs.DERIVED_DIR
    assert bs.SYNTHETIC_DERIVED_DIR == bs.REPO_ROOT / "data" / "derived" / "synthetic"
    for name in ("train_snapshot.csv", "validation_snapshot.csv", "test_snapshot.csv",
                 "feature_manifest.json", "snapshot_metadata.json", "validation_report.json"):
        assert (bs.SYNTHETIC_DERIVED_DIR / name).exists(), f"missing {name} in synthetic output dir"


# ---- 4. Original outputs cannot be overwritten by a synthetic run ----

def test_original_outputs_not_overwritten_by_synthetic_run():
    """The live data/derived/*.csv and feature_manifest.json/validation_report.json
    (already generated by the original-dataset Phase 3 run, prior to
    Phase 4C) must be byte-identical to the permanently archived
    data/derived/original/ copy -- proving the synthetic run in this phase
    never touched them. snapshot_metadata.json is checked separately
    (test_original_metadata_core_content_unchanged) with content-level
    rather than byte-level equality, because it is expected to gain the
    new dataset_id/synthetic fields (backward-compatible, same values as
    before) whenever any test in this suite re-invokes bs.main() with its
    default arguments -- that is a desired consequence of the Phase 4C
    code change, not data drift. The snapshot CSVs and the manifest/report
    are untouched by that field addition."""
    for name in ("train_snapshot.csv", "validation_snapshot.csv", "test_snapshot.csv",
                 "feature_manifest.json", "validation_report.json"):
        live = bs.DERIVED_DIR / name
        archived = bs.DERIVED_DIR / "original" / name
        assert _sha256(live) == _sha256(archived), f"{name}: live data/derived/ diverged from archived data/derived/original/"


def test_original_metadata_core_content_unchanged():
    """Every field present in the archived (pre-Phase-4C) metadata must
    still have the identical value in the live, possibly-regenerated
    metadata -- only NEW fields (dataset_id, synthetic) may have been
    added; nothing existing may have changed."""
    archived = json.loads((bs.DERIVED_DIR / "original" / "snapshot_metadata.json").read_text())
    live = json.loads((bs.DERIVED_DIR / "snapshot_metadata.json").read_text())
    for key, value in archived.items():
        if key == "generated_at_utc":
            continue  # a timestamp is expected to differ on regeneration
        assert live.get(key) == value, f"metadata field {key!r} changed: {value!r} -> {live.get(key)!r}"
    assert live.get("dataset_id") == "original"
    assert live.get("synthetic") is False


def test_archived_original_matches_recorded_hashes():
    for name, expected in EXPECTED_ARCHIVED_ORIGINAL_HASHES.items():
        actual = _sha256(bs.DERIVED_DIR / "original" / name)
        assert actual == expected, f"data/derived/original/{name} hash drifted from the Phase 4C baseline"


# ---- 5/6. Dataset identity appears in metadata; synthetic says synthetic=true ----

def test_synthetic_metadata_has_correct_dataset_identity():
    metadata = json.loads((bs.SYNTHETIC_DERIVED_DIR / "snapshot_metadata.json").read_text())
    assert metadata["dataset_id"] == "synthetic_uc07_v1"
    assert metadata["synthetic"] is True


def test_dataset_identity_defaults_to_original_when_unspecified(tmp_path):
    result = bs.main(output_dir=tmp_path / "default_args_run")  # no dataset_id/synthetic passed
    assert result["metadata"]["dataset_id"] == "original"
    assert result["metadata"]["synthetic"] is False


# ---- 7. Original (archived) metadata remains unchanged ----

def test_original_archived_metadata_unchanged():
    metadata = json.loads((bs.DERIVED_DIR / "original" / "snapshot_metadata.json").read_text())
    # This file predates the dataset_id/synthetic fields (Phase 3/4/4B
    # generated it with the pre-Phase-4C code) -- it must NOT have been
    # silently rewritten to add them.
    assert "dataset_id" not in metadata
    assert "synthetic" not in metadata
    assert metadata["target_column"] == "future_potentially_avoidable_ed_90d"


# ---- 8. Feature schema is reproducible (same schema as original, TRAIN/VAL/TEST consistent) ----

def test_synthetic_feature_schema_matches_original_and_is_internally_consistent():
    orig_manifest = json.loads((bs.DERIVED_DIR / "original" / "feature_manifest.json").read_text())
    syn_manifest = json.loads((bs.SYNTHETIC_DERIVED_DIR / "feature_manifest.json").read_text())
    orig_features = sorted(f["feature_name"] for f in orig_manifest["features"])
    syn_features = sorted(f["feature_name"] for f in syn_manifest["features"])
    assert orig_features == syn_features  # same 59-feature schema, same PIT implementation

    train = pd.read_csv(bs.SYNTHETIC_DERIVED_DIR / "train_snapshot.csv")
    val = pd.read_csv(bs.SYNTHETIC_DERIVED_DIR / "validation_snapshot.csv")
    test = pd.read_csv(bs.SYNTHETIC_DERIVED_DIR / "test_snapshot.csv")
    assert list(train.columns) == list(val.columns) == list(test.columns)


# ---- 9. All temporal leakage checks pass (synthetic) ----

def test_synthetic_leakage_checks_all_passed():
    report = json.loads((bs.SYNTHETIC_DERIVED_DIR / "validation_report.json").read_text())
    assert report["all_passed"] is True
    for snapshot_name, checks in report["per_snapshot"].items():
        failed = [name for name, result in checks.items() if not result.get("passed", True)]
        assert failed == [], f"{snapshot_name} has failed leakage checks: {failed}"
    assert report["cross_snapshot"]["schema_consistency"]["passed"] is True


def test_synthetic_no_legacy_or_diagnosis_columns():
    train = pd.read_csv(bs.SYNTHETIC_DERIVED_DIR / "train_snapshot.csv")
    assert "frequent_ED_user" not in train.columns
    assert not any(c.startswith("diagnosis_") for c in train.columns)


def test_synthetic_target_not_forced_to_original_prevalence():
    """Prevalence must be whatever the synthetic data naturally produces --
    this test only documents that it is NOT artificially pinned to
    original's ~9%, not that any specific value is required."""
    train = pd.read_csv(bs.SYNTHETIC_DERIVED_DIR / "train_snapshot.csv")
    prevalence = train["future_potentially_avoidable_ed_90d"].mean()
    assert 0.0 < prevalence < 1.0  # sanity: a real, non-degenerate binary target


# ---- 10. Raw source CSVs remain unchanged (both trios) ----

def test_raw_source_csvs_unchanged_original():
    for path in (bs.RAW_MEMBERS, bs.RAW_ED, bs.RAW_CARE):
        assert _sha256(path) == EXPECTED_ORIGINAL_RAW_HASHES[path.name]


def test_raw_source_csvs_unchanged_synthetic():
    for path in (bs.SYNTHETIC_RAW_MEMBERS, bs.SYNTHETIC_RAW_ED, bs.SYNTHETIC_RAW_CARE):
        assert _sha256(path) == EXPECTED_SYNTHETIC_RAW_HASHES[path.name]


def test_synthetic_run_hashes_before_after_match():
    """Re-verifies the synthetic build's own before/after hash guard using
    a fresh run into a throwaway directory."""
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        result = bs.main(
            members_path=bs.SYNTHETIC_RAW_MEMBERS, ed_path=bs.SYNTHETIC_RAW_ED, care_path=bs.SYNTHETIC_RAW_CARE,
            output_dir=tmp, dataset_id="synthetic_uc07_v1", synthetic=True,
        )
        assert result["raw_hashes_before"] == result["raw_hashes_after"] == EXPECTED_SYNTHETIC_RAW_HASHES


# ---- 11. Existing uc07-risk-v1 artifact remains unchanged ----

def test_v1_model_artifact_unchanged():
    artifact = joblib.load(bs.REPO_ROOT / "backend" / "models" / "uc07_risk_v1_model.joblib")
    assert artifact["model_version"] == "uc07-risk-v1"
    assert artifact["target"] == "future_potentially_avoidable_ed_90d"
    assert len(artifact["feature_columns"]) == 59
