"""
care_navigation.py
-------------------
AGENT 2 -- Care Navigation Agent.

Responsibility: determine an appropriate NON-EMERGENCY navigation
opportunity (PRIMARY_CARE / URGENT_CARE / TELEHEALTH / CARE_MANAGEMENT /
NO_PROACTIVE_NAVIGATION) using the risk tier plus historical
utilization/access/chronic-burden signals. Risk score is one input among
several -- it never solely determines the destination (per
docs/02_UC07_AND_DATA_DESIGN.md and the Phase 5 spec).

This agent MUST NOT:
    - mark anything CLEAR / CAUTION / OVERRIDE
    - see or use CurrentSafetyContext (no emergency-clearance authority)
    - produce emergency-discouraging language
Enforced by construction: `decide()` below takes no CurrentSafetyContext
parameter at all -- it is structurally impossible for this agent to base
a decision on current safety information it was never given.

This is NOT an emergency triage engine. It identifies potential future
navigation opportunities; it never denies or discourages emergency care.
"""
from __future__ import annotations

import pandas as pd

from contracts import NavigationDecision, NavigationDestination, ReasonCode, RiskTier

# Thresholds used by the rule logic below -- distances in miles, counts in
# visits, all read directly from the member's point-in-time feature row.
# These are navigation-logic constants, independent of and not to be
# confused with the risk model's own moderate/high probability thresholds.
ACCESS_BARRIER_DISTANCE_MILES = 10.0
CLOSE_ACCESS_DISTANCE_MILES = 10.0
CHRONIC_COMPLEXITY_BURDEN = 2
REPEATED_UTILIZATION_COUNT = 2


def _get(row: pd.Series, col: str, default=0):
    value = row.get(col, default)
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return default
    return value


def decide(member_id: str, risk_tier: RiskTier, features_row: pd.Series) -> NavigationDecision:
    """
    Deterministic, ordered rule tree. Priority order (highest first):
    CARE_MANAGEMENT -> TELEHEALTH -> URGENT_CARE -> PRIMARY_CARE ->
    NO_PROACTIVE_NAVIGATION. Every branch attaches explicit reason codes;
    the human-readable explanation is derived deterministically from them
    (never generated by an LLM).
    """
    transportation_barrier = int(_get(features_row, "transportation_barrier", 0))
    telehealth_available = int(_get(features_row, "telehealth_available", 0))
    pcp_distance = float(_get(features_row, "pcp_distance_miles", 99.0))
    urgent_distance = float(_get(features_row, "urgent_care_distance_miles", 99.0))
    clinical_burden = float(_get(features_row, "clinical_burden", 0))
    prior_ed_count = float(_get(features_row, "prior_ed_count_270d", 0))
    prior_avoidable_ed_count = float(_get(features_row, "prior_potentially_avoidable_ed_count_270d", 0))
    prior_pcp_count = float(_get(features_row, "prior_pcp_count_270d", 0))
    has_prior_care_management = int(_get(features_row, "has_prior_care_management", 0))

    has_access_barrier = bool(
        transportation_barrier == 1 or pcp_distance > ACCESS_BARRIER_DISTANCE_MILES or urgent_distance > ACCESS_BARRIER_DISTANCE_MILES
    )
    has_repeated_utilization = bool(prior_ed_count >= REPEATED_UTILIZATION_COUNT or prior_avoidable_ed_count >= REPEATED_UTILIZATION_COUNT)
    has_chronic_complexity = bool(clinical_burden >= CHRONIC_COMPLEXITY_BURDEN)
    elevated_risk = risk_tier in (RiskTier.MODERATE, RiskTier.HIGH)

    # ---- CARE_MANAGEMENT: elevated risk or repeated utilization, PLUS a
    # complexity/access/continuity signal. Never triggered by risk alone. ----
    complexity_signal = has_chronic_complexity or transportation_barrier == 1 or pcp_distance > ACCESS_BARRIER_DISTANCE_MILES or has_prior_care_management == 1
    if (elevated_risk or has_repeated_utilization) and complexity_signal:
        reasons = []
        if elevated_risk:
            reasons.append(ReasonCode.ELEVATED_FUTURE_RISK)
        if has_repeated_utilization:
            reasons.append(ReasonCode.REPEATED_LOWER_ACUITY_HISTORY)
        if has_chronic_complexity:
            reasons.append(ReasonCode.CHRONIC_COMPLEXITY)
        if transportation_barrier == 1:
            reasons.append(ReasonCode.TRANSPORTATION_BARRIER)
        if pcp_distance > ACCESS_BARRIER_DISTANCE_MILES:
            reasons.append(ReasonCode.LIMITED_PCP_ACCESS)
        if has_prior_care_management == 1:
            reasons.append(ReasonCode.PRIOR_CM_ENGAGEMENT)
        return NavigationDecision(
            member_id=member_id,
            destination=NavigationDestination.CARE_MANAGEMENT,
            reason_codes=reasons,
            explanation=_build_explanation(NavigationDestination.CARE_MANAGEMENT, reasons),
        )

    # ---- TELEHEALTH: available, and an access barrier makes it useful. ----
    if telehealth_available == 1 and has_access_barrier:
        reasons = [ReasonCode.TELEHEALTH_AVAILABLE]
        if transportation_barrier == 1:
            reasons.append(ReasonCode.TRANSPORTATION_BARRIER)
        if pcp_distance > ACCESS_BARRIER_DISTANCE_MILES or urgent_distance > ACCESS_BARRIER_DISTANCE_MILES:
            reasons.append(ReasonCode.LIMITED_PCP_ACCESS)
        if elevated_risk:
            reasons.append(ReasonCode.ELEVATED_FUTURE_RISK)
        return NavigationDecision(
            member_id=member_id,
            destination=NavigationDestination.TELEHEALTH,
            reason_codes=reasons,
            explanation=_build_explanation(NavigationDestination.TELEHEALTH, reasons),
        )

    # ---- URGENT_CARE: materially better access than PCP, some navigation
    # opportunity exists (elevated risk or repeated utilization). ----
    if urgent_distance < pcp_distance and (elevated_risk or has_repeated_utilization):
        reasons = [ReasonCode.URGENT_CARE_ACCESS_ADVANTAGE]
        if elevated_risk:
            reasons.append(ReasonCode.ELEVATED_FUTURE_RISK)
        if has_repeated_utilization:
            reasons.append(ReasonCode.REPEATED_LOWER_ACUITY_HISTORY)
        return NavigationDecision(
            member_id=member_id,
            destination=NavigationDestination.URGENT_CARE,
            reason_codes=reasons,
            explanation=_build_explanation(NavigationDestination.URGENT_CARE, reasons),
        )

    # ---- PRIMARY_CARE: reasonably accessible, continuity/follow-up opportunity. ----
    continuity_opportunity = prior_pcp_count > 0 or prior_ed_count >= 1
    if pcp_distance <= CLOSE_ACCESS_DISTANCE_MILES and continuity_opportunity and (elevated_risk or has_repeated_utilization or prior_pcp_count > 0):
        reasons = [ReasonCode.OUTPATIENT_CONTINUITY_OPPORTUNITY]
        if elevated_risk:
            reasons.append(ReasonCode.ELEVATED_FUTURE_RISK)
        if has_repeated_utilization:
            reasons.append(ReasonCode.REPEATED_LOWER_ACUITY_HISTORY)
        return NavigationDecision(
            member_id=member_id,
            destination=NavigationDestination.PRIMARY_CARE,
            reason_codes=reasons,
            explanation=_build_explanation(NavigationDestination.PRIMARY_CARE, reasons),
        )

    # ---- Fallback for LOW risk with no clear opportunity. ----
    return NavigationDecision(
        member_id=member_id,
        destination=NavigationDestination.NO_PROACTIVE_NAVIGATION,
        reason_codes=[ReasonCode.NO_OPPORTUNITY_IDENTIFIED],
        explanation=_build_explanation(NavigationDestination.NO_PROACTIVE_NAVIGATION, [ReasonCode.NO_OPPORTUNITY_IDENTIFIED]),
    )


_REASON_PHRASES: dict[ReasonCode, str] = {
    ReasonCode.ELEVATED_FUTURE_RISK: "an elevated predicted likelihood of future potentially avoidable ED use",
    ReasonCode.REPEATED_LOWER_ACUITY_HISTORY: "a pattern of repeated lower-acuity utilization",
    ReasonCode.TRANSPORTATION_BARRIER: "a reported transportation barrier",
    ReasonCode.LIMITED_PCP_ACCESS: "limited primary care access",
    ReasonCode.TELEHEALTH_AVAILABLE: "telehealth being available",
    ReasonCode.CHRONIC_COMPLEXITY: "chronic condition complexity",
    ReasonCode.PRIOR_CM_ENGAGEMENT: "prior Care Management engagement",
    ReasonCode.OUTPATIENT_CONTINUITY_OPPORTUNITY: "an opportunity for continued outpatient follow-up",
    ReasonCode.URGENT_CARE_ACCESS_ADVANTAGE: "meaningfully better access to urgent care than to primary care",
    ReasonCode.NO_OPPORTUNITY_IDENTIFIED: "no meaningful navigation opportunity was identified at this time",
}

_DESTINATION_LABELS: dict[NavigationDestination, str] = {
    NavigationDestination.CARE_MANAGEMENT: "a Care Management outreach review",
    NavigationDestination.TELEHEALTH: "a future telehealth visit",
    NavigationDestination.URGENT_CARE: "a future urgent care visit for non-emergency needs",
    NavigationDestination.PRIMARY_CARE: "a future primary care follow-up",
    NavigationDestination.NO_PROACTIVE_NAVIGATION: "no proactive navigation step",
}


def _build_explanation(destination: NavigationDestination, reasons: list[ReasonCode]) -> str:
    reason_text = "; ".join(_REASON_PHRASES[r] for r in reasons)
    if destination == NavigationDestination.NO_PROACTIVE_NAVIGATION:
        return f"Based on this member's current pattern, {reason_text}."
    return f"Based on {reason_text}, {_DESTINATION_LABELS[destination]} may be a useful future, non-emergency option."
