"""initial schema

Revision ID: 7dad1aa10b9d
Revises: 
Create Date: 2026-08-18 10:46:47.802902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dad1aa10b9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('populations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_members_filename', sa.String(length=255), nullable=True),
    sa.Column('source_ed_visits_filename', sa.String(length=255), nullable=True),
    sa.Column('source_care_filename', sa.String(length=255), nullable=True),
    sa.Column('source_safety_context_filename', sa.String(length=255), nullable=True),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('synthetic_model', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_populations_owner_created', 'populations', ['owner_user_id', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('contributing_factors_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('synthetic_model', sa.Boolean(), nullable=False),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('moderate_threshold', sa.Float(), nullable=False),
    sa.Column('high_threshold', sa.Float(), nullable=False),
    sa.Column('explanation_factors_json', sa.Text(), nullable=False),
    sa.Column('explanation_method', sa.String(length=50), nullable=False),
    sa.Column('explanation_causal', sa.Boolean(), nullable=False),
    sa.Column('navigation_destination', sa.String(length=50), nullable=True),
    sa.Column('navigation_reason_codes_json', sa.Text(), nullable=False),
    sa.Column('navigation_explanation', sa.Text(), nullable=False),
    sa.Column('safety_state', sa.String(length=20), nullable=False),
    sa.Column('safety_override', sa.Boolean(), nullable=False),
    sa.Column('safety_message', sa.Text(), nullable=False),
    sa.Column('safety_blocked_phrases_json', sa.Text(), nullable=False),
    sa.Column('safety_context_completeness', sa.String(length=20), nullable=False),
    sa.Column('safety_context_source', sa.String(length=30), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_id', 'member_id', name='uq_analysis_results_member')
    )
    op.create_index('ix_analysis_results_population_member', 'analysis_results', ['population_id', 'member_id'], unique=False)
    op.create_index('ix_analysis_results_population_safety', 'analysis_results', ['population_id', 'safety_state'], unique=False)
    op.create_index('ix_analysis_results_population_tier', 'analysis_results', ['population_id', 'tier'], unique=False)
    op.create_table('population_care_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('care_id', sa.String(length=64), nullable=True),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('care_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_population_care_records_population_member', 'population_care_records', ['population_id', 'member_id'], unique=False)
    op.create_table('population_ed_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.String(length=64), nullable=True),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('triage_level', sa.Integer(), nullable=False),
    sa.Column('admitted', sa.Integer(), nullable=False),
    sa.Column('icu', sa.Integer(), nullable=False),
    sa.Column('major_procedure', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('red_flag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_population_ed_visits_population_member', 'population_ed_visits', ['population_id', 'member_id'], unique=False)
    op.create_table('population_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('diabetes', sa.Integer(), nullable=False),
    sa.Column('copd', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Integer(), nullable=False),
    sa.Column('chf', sa.Integer(), nullable=False),
    sa.Column('asthma', sa.Integer(), nullable=False),
    sa.Column('ckd', sa.Integer(), nullable=False),
    sa.Column('num_chronic_conditions', sa.Integer(), nullable=False),
    sa.Column('transportation_barrier', sa.Integer(), nullable=False),
    sa.Column('telehealth_available', sa.Integer(), nullable=False),
    sa.Column('pcp_distance_miles', sa.Float(), nullable=False),
    sa.Column('urgent_care_distance_miles', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_id', 'member_id', name='uq_population_members_member')
    )
    op.create_index('ix_population_members_population_member', 'population_members', ['population_id', 'member_id'], unique=False)
    op.create_table('population_safety_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('red_flag', sa.Integer(), nullable=True),
    sa.Column('icu', sa.Integer(), nullable=True),
    sa.Column('admitted', sa.Integer(), nullable=True),
    sa.Column('major_procedure', sa.Integer(), nullable=True),
    sa.Column('triage_level', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_id', 'member_id', name='uq_population_safety_context_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_safety_context')
    op.drop_index('ix_population_members_population_member', table_name='population_members')
    op.drop_table('population_members')
    op.drop_index('ix_population_ed_visits_population_member', table_name='population_ed_visits')
    op.drop_table('population_ed_visits')
    op.drop_index('ix_population_care_records_population_member', table_name='population_care_records')
    op.drop_table('population_care_records')
    op.drop_index('ix_analysis_results_population_tier', table_name='analysis_results')
    op.drop_index('ix_analysis_results_population_safety', table_name='analysis_results')
    op.drop_index('ix_analysis_results_population_member', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_populations_owner_created', table_name='populations')
    op.drop_table('populations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
